version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: postgres
